import Header from "@/components/Common/Header";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Stage",
  description: "Generated by create next app",
};

const CommonLayout = async ({ children }: { children: React.ReactNode }) => {
  return (
    <div>
      <Header />
      {children}
    </div>
  );
};

export default CommonLayout;
